---
- include: ../../redis/tasks/main.yml
  vars:
    redis:
      config_path: /etc/redis/redis.conf
      user: redis
      group: redis
      config:
        bind: 127.0.0.1
        port: 6379
        loglevel: notice
        logfile: /var/log/redis/redis-server.log
        databases: 16
        maxmemory: 256mb
        maxmemory_policy: volatile-lru
        appendonly: no
        appendfsync: everysec
        dir: /var/lib/redis
        save: []

- name: Install sidekiq init script
  template:
    src: sidekiq_init.j2
    dest: "/etc/init.d/sidekiq_{{ app_name }}"
    force: yes
    mode: 755
    owner: "{{ user }}"

- name: Install sidekiq monit config
  template:
    src: sidekiq_monit.j2
    dest: "/etc/monit/conf.d/sidekiq_{{ app_name }}.conf"